// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC0Mr3rd_nGX_fAH9LAS4225fiIWn-Tko',
    appId: '1:831100284886:web:bf416a404bbd0134ce3e77',
    messagingSenderId: '831100284886',
    projectId: 'hairaiapp-2e6ce',
    authDomain: 'hairaiapp-2e6ce.firebaseapp.com',
    storageBucket: 'hairaiapp-2e6ce.firebasestorage.app',
    measurementId: 'G-63RFKKC7C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtgEKByq6tbPGYWzLJ6GC1V4HQTeEpHmo',
    appId: '1:831100284886:android:8295e580cc3ab475ce3e77',
    messagingSenderId: '831100284886',
    projectId: 'hairaiapp-2e6ce',
    storageBucket: 'hairaiapp-2e6ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGSlAhVnG3urD4A1DfiGgcojcE7Y_d6c',
    appId: '1:831100284886:ios:4987288bda3f58bece3e77',
    messagingSenderId: '831100284886',
    projectId: 'hairaiapp-2e6ce',
    storageBucket: 'hairaiapp-2e6ce.firebasestorage.app',
    iosClientId: '831100284886-ifs3p2ht2mb3sqrb8mv5tcesmu46h1tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGSlAhVnG3urD4A1DfiGgcojcE7Y_d6c',
    appId: '1:831100284886:ios:4987288bda3f58bece3e77',
    messagingSenderId: '831100284886',
    projectId: 'hairaiapp-2e6ce',
    storageBucket: 'hairaiapp-2e6ce.firebasestorage.app',
    iosClientId: '831100284886-ifs3p2ht2mb3sqrb8mv5tcesmu46h1tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC0Mr3rd_nGX_fAH9LAS4225fiIWn-Tko',
    appId: '1:831100284886:web:9efe7cc15b04645fce3e77',
    messagingSenderId: '831100284886',
    projectId: 'hairaiapp-2e6ce',
    authDomain: 'hairaiapp-2e6ce.firebaseapp.com',
    storageBucket: 'hairaiapp-2e6ce.firebasestorage.app',
    measurementId: 'G-Q6THNK3Q5T',
  );
}
